name: "WelcomeMat.co"
description: "Copy & Paste ASCII Art Welcome Mats for your HTML"

url: "http://welcomemat.co"

paginate: 100

permalink: pretty

exclude: ['config.rb', 'README.md', 'scss', 'welcomemat.co']